name: 🐞 Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue to improve StatGPT.
        Please fill in as much of the following form as you're able.
  - type: input
    attributes:
      label: StatGPT Helm version
      description: Helm Chart version
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: Enter details about your bug.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible please provide textual output instead of screenshots.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible please provide textual output instead of screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
