name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: v3.13.0

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml 2>/dev/null)
          if [[ -n "$changed" ]]; then
            echo "$changed" # to show in the logs
            {
              echo 'changed<<EOF'
              echo "${changed}"
              echo EOF
            } >>$GITHUB_OUTPUT
              echo "is_changed=true" >>$GITHUB_OUTPUT
          fi

      - name: Check documentation is up-to-date
        if: steps.list-changed.outputs.is_changed == 'true'
        env:
          HELM_DOCS_VERSION: v1.11.3
          CHANGED_CHARTS: ${{ steps.list-changed.outputs.changed }}
        run: |
          #!/bin/bash
          set -e

          echo "=== DEBUGGING HELM-DOCS CHECK ==="
          echo "Changed charts: $CHANGED_CHARTS"
          echo "Working directory: $(pwd)"
          echo "Git status before helm-docs:"
          git status --porcelain

          IFS=$'\n'
          for chart in $CHANGED_CHARTS; do
            echo ""
            echo "=== Processing chart: ${chart} ==="
            echo "Chart directory contents:"
            ls -la "${chart}/"

            echo ""
            echo "README.md before helm-docs (if exists):"
            if [[ -f "${chart}/README.md" ]]; then
              echo "File exists, size: $(wc -c < ${chart}/README.md) bytes"
              echo "Line endings check:"
              file "${chart}/README.md"
              echo "Last few lines:"
              tail -3 "${chart}/README.md" | cat -A
            else
              echo "README.md does not exist"
            fi

            echo ""
            echo "Running helm-docs for ${chart}..."
            docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:${HELM_DOCS_VERSION} --chart-search-root=${chart}

            echo ""
            echo "README.md after helm-docs:"
            if [[ -f "${chart}/README.md" ]]; then
              echo "File exists, size: $(wc -c < ${chart}/README.md) bytes"
              echo "Line endings check:"
              file "${chart}/README.md"
              echo "Last few lines:"
              tail -3 "${chart}/README.md" | cat -A
            else
              echo "README.md still does not exist!"
            fi

            echo ""
            echo "Git status after helm-docs for ${chart}:"
            git status --porcelain "${chart}/README.md"

            echo ""
            echo "Git diff for ${chart}/README.md:"
            if git diff --quiet "${chart}/README.md"; then
              echo "No differences detected by git diff"
            else
              echo "Differences found:"
              git diff "${chart}/README.md" | head -20
              echo ""
              echo "Detailed diff with whitespace visible:"
              git diff --ws-error-highlight=all "${chart}/README.md" | head -20
            fi

            echo ""
            echo "Checking git status porcelain output:"
            porcelain_output=$(git status --porcelain "${chart}/README.md")
            echo "Porcelain output: '${porcelain_output}'"
            echo "Length of porcelain output: ${#porcelain_output}"

            if [[ -n "$porcelain_output" ]]; then
              echo "::error::Documentation for ${chart} is not up-to-date. Please run \`helm-docs\` and commit changes!"
              echo "::error::Git detected changes in the README.md file"
              exit 1
            else
              echo "✅ Documentation for ${chart} is up-to-date."
            fi
          done

          echo ""
          echo "=== FINAL GIT STATUS ==="
          git status --porcelain

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.is_changed == 'true'
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        if: steps.list-changed.outputs.is_changed == 'true'
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.is_changed == 'true'
        run: ct install --config ct.yaml
